# Generated by Django 3.2.6 on 2021-08-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('propoints_needed_min', models.IntegerField()),
                ('points_needed_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiplicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha', models.IntegerField()),
                ('multiplicator', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('points_needed', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Team_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('racha', models.IntegerField()),
                ('point_earned', models.IntegerField()),
                ('points_available', models.IntegerField()),
                ('workspace_id', models.IntegerField()),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Badges_TeamUser', to='Climb.badge')),
                ('multiplicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Multiplicators_TeamUser', to='Climb.multiplicator')),
                ('rewards_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rewards_TeamUser', to='Climb.rewards')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Roles_TeamUser', to='Climb.role')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace_team_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team_users_Workspace_team_user', to='Climb.team_user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Goals_Workspace', to='Climb.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('type', models.CharField(choices=[('To Do', 'to do'), ('Done', 'done'), ('Delay', 'delay'), ('Refused', 'refused')], default='To Do', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('messages', models.CharField(max_length=255)),
                ('messages_refused', models.CharField(max_length=255)),
                ('team_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team_users_Task', to='Climb.team_user')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tasks_Goal', to='Climb.task'),
        ),
        migrations.CreateModel(
            name='Company_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Badges_Company_user', to='Climb.badge')),
                ('multiplicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Multiplicators_Company_user', to='Climb.multiplicator')),
                ('rewards_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rewards_Company_user', to='Climb.rewards')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Roles_Company_user', to='Climb.role')),
                ('team_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team_users_Company_user', to='Climb.team_user')),
                ('workspace_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Workspaces_Company_user', to='Climb.workspace')),
            ],
        ),
    ]
