# Generated by Django 3.2.6 on 2021-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message_refused',
            field=models.TextField(blank=True, null=True),
        ),
    ]
