# Generated by Django 3.2.6 on 2021-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
