# Generated by Django 3.2.6 on 2021-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0002_alter_companyuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/company_user'),
        ),
    ]
