# Generated by Django 3.2.6 on 2021-09-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0002_alter_task_message_refused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
