# Generated by Django 3.2.6 on 2021-09-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0002_auto_20210908_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
