# Generated by Django 3.2.6 on 2021-09-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0003_auto_20210913_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
