# Generated by Django 3.2.6 on 2021-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0003_alter_companyuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/badge'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/reward'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/team_user'),
        ),
    ]
