# Generated by Django 3.2.6 on 2021-09-01 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0003_alter_reward_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Climb.role'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
