# Generated by Django 3.2.6 on 2021-08-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0004_auto_20210820_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_goal', to='Climb.goal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='message_refused',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_team_user', to='Climb.teamuser'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='multiplicator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_users_mult', to='Climb.multiplicator'),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='points_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamuser',
            name='reward_id',
            field=models.ManyToManyField(blank=True, null=True, to='Climb.Reward'),
        ),
    ]
