# Generated by Django 3.2.6 on 2021-09-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0005_alter_badge_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
    ]
