# Generated by Django 3.2.6 on 2021-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Climb', '0005_auto_20210820_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='reward_id',
            field=models.ManyToManyField(to='Climb.Reward'),
        ),
    ]
